# version: '2'
version: '2'
services:
  master:
    build: .
    container_name: master
    command:
      bash -c "source my_entrypoint.sh roscore"

  talker:
    build: .
    container_name: talker
    environment:
      - "ROS_HOSTNAME=talker"
      - "ROS_MASTER_URI=http://master:11311/"
    command:
      bash -c "source my_entrypoint.sh rosrun lillypkg testpub.py"

  listener:
    build: .
    container_name: listener
    environment:
      - "ROS_HOSTNAME=listener"
      - "ROS_MASTER_URI=http://master:11311/"
    command:
      bash -c "source my_entrypoint.sh rosrun lillypkg testpub.py"
