// Generated by gencpp from file irisbot/DiscoveryRequest.msg
// DO NOT EDIT!


#ifndef IRISBOT_MESSAGE_DISCOVERYREQUEST_H
#define IRISBOT_MESSAGE_DISCOVERYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <irisbot/Node.h>

namespace irisbot
{
template <class ContainerAllocator>
struct DiscoveryRequest_
{
  typedef DiscoveryRequest_<ContainerAllocator> Type;

  DiscoveryRequest_()
    : myself()  {
    }
  DiscoveryRequest_(const ContainerAllocator& _alloc)
    : myself(_alloc)  {
  (void)_alloc;
    }



   typedef  ::irisbot::Node_<ContainerAllocator>  _myself_type;
  _myself_type myself;





  typedef boost::shared_ptr< ::irisbot::DiscoveryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irisbot::DiscoveryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DiscoveryRequest_

typedef ::irisbot::DiscoveryRequest_<std::allocator<void> > DiscoveryRequest;

typedef boost::shared_ptr< ::irisbot::DiscoveryRequest > DiscoveryRequestPtr;
typedef boost::shared_ptr< ::irisbot::DiscoveryRequest const> DiscoveryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irisbot::DiscoveryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irisbot::DiscoveryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace irisbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'irisbot': ['/home/lilly/Desktop/ROSws/src/irisbot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::irisbot::DiscoveryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irisbot::DiscoveryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irisbot::DiscoveryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irisbot::DiscoveryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irisbot::DiscoveryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irisbot::DiscoveryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irisbot::DiscoveryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b285f325119edace42114f4aa36c582c";
  }

  static const char* value(const ::irisbot::DiscoveryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb285f325119edaceULL;
  static const uint64_t static_value2 = 0x42114f4aa36c582cULL;
};

template<class ContainerAllocator>
struct DataType< ::irisbot::DiscoveryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irisbot/DiscoveryRequest";
  }

  static const char* value(const ::irisbot::DiscoveryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irisbot::DiscoveryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Node myself\n\
\n\
================================================================================\n\
MSG: irisbot/Node\n\
int32 ID\n\
int32 addr\n\
string role\n\
";
  }

  static const char* value(const ::irisbot::DiscoveryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irisbot::DiscoveryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.myself);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DiscoveryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irisbot::DiscoveryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irisbot::DiscoveryRequest_<ContainerAllocator>& v)
  {
    s << indent << "myself: ";
    s << std::endl;
    Printer< ::irisbot::Node_<ContainerAllocator> >::stream(s, indent + "  ", v.myself);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRISBOT_MESSAGE_DISCOVERYREQUEST_H
