// Generated by gencpp from file irisbot/DriveCmd.msg
// DO NOT EDIT!


#ifndef IRISBOT_MESSAGE_DRIVECMD_H
#define IRISBOT_MESSAGE_DRIVECMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace irisbot
{
template <class ContainerAllocator>
struct DriveCmd_
{
  typedef DriveCmd_<ContainerAllocator> Type;

  DriveCmd_()
    : speed(0)
    , distance(0)  {
    }
  DriveCmd_(const ContainerAllocator& _alloc)
    : speed(0)
    , distance(0)  {
  (void)_alloc;
    }



   typedef int32_t _speed_type;
  _speed_type speed;

   typedef int32_t _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::irisbot::DriveCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irisbot::DriveCmd_<ContainerAllocator> const> ConstPtr;

}; // struct DriveCmd_

typedef ::irisbot::DriveCmd_<std::allocator<void> > DriveCmd;

typedef boost::shared_ptr< ::irisbot::DriveCmd > DriveCmdPtr;
typedef boost::shared_ptr< ::irisbot::DriveCmd const> DriveCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irisbot::DriveCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irisbot::DriveCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace irisbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'irisbot': ['/home/lilly/Desktop/ROSws/src/irisbot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::irisbot::DriveCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irisbot::DriveCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irisbot::DriveCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irisbot::DriveCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irisbot::DriveCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irisbot::DriveCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irisbot::DriveCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23af4beb5c0ba546ff12a4473f8899f4";
  }

  static const char* value(const ::irisbot::DriveCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23af4beb5c0ba546ULL;
  static const uint64_t static_value2 = 0xff12a4473f8899f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::irisbot::DriveCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irisbot/DriveCmd";
  }

  static const char* value(const ::irisbot::DriveCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irisbot::DriveCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 speed\n\
int32 distance\n\
";
  }

  static const char* value(const ::irisbot::DriveCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irisbot::DriveCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irisbot::DriveCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irisbot::DriveCmd_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed);
    s << indent << "distance: ";
    Printer<int32_t>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRISBOT_MESSAGE_DRIVECMD_H
