// Generated by gencpp from file irisbot/LocalizeRequest.msg
// DO NOT EDIT!


#ifndef IRISBOT_MESSAGE_LOCALIZEREQUEST_H
#define IRISBOT_MESSAGE_LOCALIZEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <irisbot/NodeLoc.h>
#include <irisbot/NodeLoc.h>
#include <irisbot/NodeLoc.h>

namespace irisbot
{
template <class ContainerAllocator>
struct LocalizeRequest_
{
  typedef LocalizeRequest_<ContainerAllocator> Type;

  LocalizeRequest_()
    : anchor1()
    , anchor2()
    , anchor3()  {
    }
  LocalizeRequest_(const ContainerAllocator& _alloc)
    : anchor1(_alloc)
    , anchor2(_alloc)
    , anchor3(_alloc)  {
  (void)_alloc;
    }



   typedef  ::irisbot::NodeLoc_<ContainerAllocator>  _anchor1_type;
  _anchor1_type anchor1;

   typedef  ::irisbot::NodeLoc_<ContainerAllocator>  _anchor2_type;
  _anchor2_type anchor2;

   typedef  ::irisbot::NodeLoc_<ContainerAllocator>  _anchor3_type;
  _anchor3_type anchor3;





  typedef boost::shared_ptr< ::irisbot::LocalizeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irisbot::LocalizeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LocalizeRequest_

typedef ::irisbot::LocalizeRequest_<std::allocator<void> > LocalizeRequest;

typedef boost::shared_ptr< ::irisbot::LocalizeRequest > LocalizeRequestPtr;
typedef boost::shared_ptr< ::irisbot::LocalizeRequest const> LocalizeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irisbot::LocalizeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irisbot::LocalizeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace irisbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'irisbot': ['/home/lilly/Desktop/ROSws/src/irisbot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::irisbot::LocalizeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irisbot::LocalizeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irisbot::LocalizeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irisbot::LocalizeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irisbot::LocalizeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irisbot::LocalizeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irisbot::LocalizeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e1df242fcf691517c198036f4f1ddf2f";
  }

  static const char* value(const ::irisbot::LocalizeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1df242fcf691517ULL;
  static const uint64_t static_value2 = 0xc198036f4f1ddf2fULL;
};

template<class ContainerAllocator>
struct DataType< ::irisbot::LocalizeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irisbot/LocalizeRequest";
  }

  static const char* value(const ::irisbot::LocalizeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irisbot::LocalizeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "NodeLoc anchor1\n\
NodeLoc anchor2\n\
NodeLoc anchor3\n\
\n\
================================================================================\n\
MSG: irisbot/NodeLoc\n\
Node node\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: irisbot/Node\n\
int32 ID\n\
int32 addr\n\
string role\n\
\n\
================================================================================\n\
MSG: irisbot/Pose\n\
float32 x\n\
float32 y\n\
float32 orientation\n\
";
  }

  static const char* value(const ::irisbot::LocalizeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irisbot::LocalizeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.anchor1);
      stream.next(m.anchor2);
      stream.next(m.anchor3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalizeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irisbot::LocalizeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irisbot::LocalizeRequest_<ContainerAllocator>& v)
  {
    s << indent << "anchor1: ";
    s << std::endl;
    Printer< ::irisbot::NodeLoc_<ContainerAllocator> >::stream(s, indent + "  ", v.anchor1);
    s << indent << "anchor2: ";
    s << std::endl;
    Printer< ::irisbot::NodeLoc_<ContainerAllocator> >::stream(s, indent + "  ", v.anchor2);
    s << indent << "anchor3: ";
    s << std::endl;
    Printer< ::irisbot::NodeLoc_<ContainerAllocator> >::stream(s, indent + "  ", v.anchor3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRISBOT_MESSAGE_LOCALIZEREQUEST_H
