// Generated by gencpp from file irisbot/Localize.msg
// DO NOT EDIT!


#ifndef IRISBOT_MESSAGE_LOCALIZE_H
#define IRISBOT_MESSAGE_LOCALIZE_H

#include <ros/service_traits.h>


#include <irisbot/LocalizeRequest.h>
#include <irisbot/LocalizeResponse.h>


namespace irisbot
{

struct Localize
{

typedef LocalizeRequest Request;
typedef LocalizeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Localize
} // namespace irisbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::irisbot::Localize > {
  static const char* value()
  {
    return "7b1f8b4ce8b7517335b67cd48d174add";
  }

  static const char* value(const ::irisbot::Localize&) { return value(); }
};

template<>
struct DataType< ::irisbot::Localize > {
  static const char* value()
  {
    return "irisbot/Localize";
  }

  static const char* value(const ::irisbot::Localize&) { return value(); }
};


// service_traits::MD5Sum< ::irisbot::LocalizeRequest> should match 
// service_traits::MD5Sum< ::irisbot::Localize > 
template<>
struct MD5Sum< ::irisbot::LocalizeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::irisbot::Localize >::value();
  }
  static const char* value(const ::irisbot::LocalizeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::irisbot::LocalizeRequest> should match 
// service_traits::DataType< ::irisbot::Localize > 
template<>
struct DataType< ::irisbot::LocalizeRequest>
{
  static const char* value()
  {
    return DataType< ::irisbot::Localize >::value();
  }
  static const char* value(const ::irisbot::LocalizeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::irisbot::LocalizeResponse> should match 
// service_traits::MD5Sum< ::irisbot::Localize > 
template<>
struct MD5Sum< ::irisbot::LocalizeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::irisbot::Localize >::value();
  }
  static const char* value(const ::irisbot::LocalizeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::irisbot::LocalizeResponse> should match 
// service_traits::DataType< ::irisbot::Localize > 
template<>
struct DataType< ::irisbot::LocalizeResponse>
{
  static const char* value()
  {
    return DataType< ::irisbot::Localize >::value();
  }
  static const char* value(const ::irisbot::LocalizeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IRISBOT_MESSAGE_LOCALIZE_H
