// Generated by gencpp from file irisbot/MoveCmd.msg
// DO NOT EDIT!


#ifndef IRISBOT_MESSAGE_MOVECMD_H
#define IRISBOT_MESSAGE_MOVECMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace irisbot
{
template <class ContainerAllocator>
struct MoveCmd_
{
  typedef MoveCmd_<ContainerAllocator> Type;

  MoveCmd_()
    : orientation(0.0)
    , speed(0.0)
    , distance(0.0)  {
    }
  MoveCmd_(const ContainerAllocator& _alloc)
    : orientation(0.0)
    , speed(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef float _orientation_type;
  _orientation_type orientation;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::irisbot::MoveCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irisbot::MoveCmd_<ContainerAllocator> const> ConstPtr;

}; // struct MoveCmd_

typedef ::irisbot::MoveCmd_<std::allocator<void> > MoveCmd;

typedef boost::shared_ptr< ::irisbot::MoveCmd > MoveCmdPtr;
typedef boost::shared_ptr< ::irisbot::MoveCmd const> MoveCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irisbot::MoveCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irisbot::MoveCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace irisbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'irisbot': ['/home/lilly/Desktop/ROSws/src/irisbot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::irisbot::MoveCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irisbot::MoveCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irisbot::MoveCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irisbot::MoveCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irisbot::MoveCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irisbot::MoveCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irisbot::MoveCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f5c5a8e2615982cda00bd1a9073b52e";
  }

  static const char* value(const ::irisbot::MoveCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f5c5a8e2615982cULL;
  static const uint64_t static_value2 = 0xda00bd1a9073b52eULL;
};

template<class ContainerAllocator>
struct DataType< ::irisbot::MoveCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irisbot/MoveCmd";
  }

  static const char* value(const ::irisbot::MoveCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irisbot::MoveCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 orientation\n\
float32 speed\n\
float32 distance\n\
";
  }

  static const char* value(const ::irisbot::MoveCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irisbot::MoveCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.orientation);
      stream.next(m.speed);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irisbot::MoveCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irisbot::MoveCmd_<ContainerAllocator>& v)
  {
    s << indent << "orientation: ";
    Printer<float>::stream(s, indent + "  ", v.orientation);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRISBOT_MESSAGE_MOVECMD_H
