// Generated by gencpp from file irisbot/GetAnchorResponse.msg
// DO NOT EDIT!


#ifndef IRISBOT_MESSAGE_GETANCHORRESPONSE_H
#define IRISBOT_MESSAGE_GETANCHORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <irisbot/NodeLoc.h>

namespace irisbot
{
template <class ContainerAllocator>
struct GetAnchorResponse_
{
  typedef GetAnchorResponse_<ContainerAllocator> Type;

  GetAnchorResponse_()
    : anchors()
    , dists()  {
    }
  GetAnchorResponse_(const ContainerAllocator& _alloc)
    : anchors(_alloc)
    , dists(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::irisbot::NodeLoc_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::irisbot::NodeLoc_<ContainerAllocator> >::other >  _anchors_type;
  _anchors_type anchors;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _dists_type;
  _dists_type dists;





  typedef boost::shared_ptr< ::irisbot::GetAnchorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irisbot::GetAnchorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetAnchorResponse_

typedef ::irisbot::GetAnchorResponse_<std::allocator<void> > GetAnchorResponse;

typedef boost::shared_ptr< ::irisbot::GetAnchorResponse > GetAnchorResponsePtr;
typedef boost::shared_ptr< ::irisbot::GetAnchorResponse const> GetAnchorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irisbot::GetAnchorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irisbot::GetAnchorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace irisbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'irisbot': ['/home/lilly/Desktop/ROSws/src/irisbot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::irisbot::GetAnchorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irisbot::GetAnchorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irisbot::GetAnchorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irisbot::GetAnchorResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irisbot::GetAnchorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irisbot::GetAnchorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irisbot::GetAnchorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bdcc41d11e382e747897694dfa86a621";
  }

  static const char* value(const ::irisbot::GetAnchorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbdcc41d11e382e74ULL;
  static const uint64_t static_value2 = 0x7897694dfa86a621ULL;
};

template<class ContainerAllocator>
struct DataType< ::irisbot::GetAnchorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irisbot/GetAnchorResponse";
  }

  static const char* value(const ::irisbot::GetAnchorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irisbot::GetAnchorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "NodeLoc[] anchors\n\
float32[] dists\n\
\n\
\n\
================================================================================\n\
MSG: irisbot/NodeLoc\n\
Node node\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: irisbot/Node\n\
int32 ID\n\
int32 addr\n\
string role\n\
\n\
================================================================================\n\
MSG: irisbot/Pose\n\
float32 x\n\
float32 y\n\
float32 orientation\n\
";
  }

  static const char* value(const ::irisbot::GetAnchorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irisbot::GetAnchorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.anchors);
      stream.next(m.dists);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAnchorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irisbot::GetAnchorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irisbot::GetAnchorResponse_<ContainerAllocator>& v)
  {
    s << indent << "anchors[]" << std::endl;
    for (size_t i = 0; i < v.anchors.size(); ++i)
    {
      s << indent << "  anchors[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::irisbot::NodeLoc_<ContainerAllocator> >::stream(s, indent + "    ", v.anchors[i]);
    }
    s << indent << "dists[]" << std::endl;
    for (size_t i = 0; i < v.dists.size(); ++i)
    {
      s << indent << "  dists[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.dists[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRISBOT_MESSAGE_GETANCHORRESPONSE_H
