// Generated by gencpp from file irisbot/GetAnchor.msg
// DO NOT EDIT!


#ifndef IRISBOT_MESSAGE_GETANCHOR_H
#define IRISBOT_MESSAGE_GETANCHOR_H

#include <ros/service_traits.h>


#include <irisbot/GetAnchorRequest.h>
#include <irisbot/GetAnchorResponse.h>


namespace irisbot
{

struct GetAnchor
{

typedef GetAnchorRequest Request;
typedef GetAnchorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAnchor
} // namespace irisbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::irisbot::GetAnchor > {
  static const char* value()
  {
    return "f752ccbb67076c1bee44990c827507b5";
  }

  static const char* value(const ::irisbot::GetAnchor&) { return value(); }
};

template<>
struct DataType< ::irisbot::GetAnchor > {
  static const char* value()
  {
    return "irisbot/GetAnchor";
  }

  static const char* value(const ::irisbot::GetAnchor&) { return value(); }
};


// service_traits::MD5Sum< ::irisbot::GetAnchorRequest> should match 
// service_traits::MD5Sum< ::irisbot::GetAnchor > 
template<>
struct MD5Sum< ::irisbot::GetAnchorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::irisbot::GetAnchor >::value();
  }
  static const char* value(const ::irisbot::GetAnchorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::irisbot::GetAnchorRequest> should match 
// service_traits::DataType< ::irisbot::GetAnchor > 
template<>
struct DataType< ::irisbot::GetAnchorRequest>
{
  static const char* value()
  {
    return DataType< ::irisbot::GetAnchor >::value();
  }
  static const char* value(const ::irisbot::GetAnchorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::irisbot::GetAnchorResponse> should match 
// service_traits::MD5Sum< ::irisbot::GetAnchor > 
template<>
struct MD5Sum< ::irisbot::GetAnchorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::irisbot::GetAnchor >::value();
  }
  static const char* value(const ::irisbot::GetAnchorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::irisbot::GetAnchorResponse> should match 
// service_traits::DataType< ::irisbot::GetAnchor > 
template<>
struct DataType< ::irisbot::GetAnchorResponse>
{
  static const char* value()
  {
    return DataType< ::irisbot::GetAnchor >::value();
  }
  static const char* value(const ::irisbot::GetAnchorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IRISBOT_MESSAGE_GETANCHOR_H
