// Generated by gencpp from file irisbot/GetAnchorRequest.msg
// DO NOT EDIT!


#ifndef IRISBOT_MESSAGE_GETANCHORREQUEST_H
#define IRISBOT_MESSAGE_GETANCHORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace irisbot
{
template <class ContainerAllocator>
struct GetAnchorRequest_
{
  typedef GetAnchorRequest_<ContainerAllocator> Type;

  GetAnchorRequest_()
    : ids()  {
    }
  GetAnchorRequest_(const ContainerAllocator& _alloc)
    : ids(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _ids_type;
  _ids_type ids;





  typedef boost::shared_ptr< ::irisbot::GetAnchorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irisbot::GetAnchorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetAnchorRequest_

typedef ::irisbot::GetAnchorRequest_<std::allocator<void> > GetAnchorRequest;

typedef boost::shared_ptr< ::irisbot::GetAnchorRequest > GetAnchorRequestPtr;
typedef boost::shared_ptr< ::irisbot::GetAnchorRequest const> GetAnchorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irisbot::GetAnchorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irisbot::GetAnchorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace irisbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'irisbot': ['/home/lilly/Desktop/ROSws/src/irisbot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::irisbot::GetAnchorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irisbot::GetAnchorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irisbot::GetAnchorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irisbot::GetAnchorRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irisbot::GetAnchorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irisbot::GetAnchorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irisbot::GetAnchorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f22efebf407aadba2ecc69df353d113";
  }

  static const char* value(const ::irisbot::GetAnchorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f22efebf407aadbULL;
  static const uint64_t static_value2 = 0xa2ecc69df353d113ULL;
};

template<class ContainerAllocator>
struct DataType< ::irisbot::GetAnchorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irisbot/GetAnchorRequest";
  }

  static const char* value(const ::irisbot::GetAnchorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irisbot::GetAnchorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] ids\n\
";
  }

  static const char* value(const ::irisbot::GetAnchorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irisbot::GetAnchorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAnchorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irisbot::GetAnchorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irisbot::GetAnchorRequest_<ContainerAllocator>& v)
  {
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRISBOT_MESSAGE_GETANCHORREQUEST_H
