// Generated by gencpp from file irisbot/NodeMsg.msg
// DO NOT EDIT!


#ifndef IRISBOT_MESSAGE_NODEMSG_H
#define IRISBOT_MESSAGE_NODEMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <irisbot/Node.h>

namespace irisbot
{
template <class ContainerAllocator>
struct NodeMsg_
{
  typedef NodeMsg_<ContainerAllocator> Type;

  NodeMsg_()
    : node()
    , message()  {
    }
  NodeMsg_(const ContainerAllocator& _alloc)
    : node(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef  ::irisbot::Node_<ContainerAllocator>  _node_type;
  _node_type node;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::irisbot::NodeMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irisbot::NodeMsg_<ContainerAllocator> const> ConstPtr;

}; // struct NodeMsg_

typedef ::irisbot::NodeMsg_<std::allocator<void> > NodeMsg;

typedef boost::shared_ptr< ::irisbot::NodeMsg > NodeMsgPtr;
typedef boost::shared_ptr< ::irisbot::NodeMsg const> NodeMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irisbot::NodeMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irisbot::NodeMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace irisbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'irisbot': ['/home/lilly/Desktop/ROSws/src/irisbot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::irisbot::NodeMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irisbot::NodeMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irisbot::NodeMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irisbot::NodeMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irisbot::NodeMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irisbot::NodeMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irisbot::NodeMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92c675d5552e0ff0444fb567ca5dc17e";
  }

  static const char* value(const ::irisbot::NodeMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92c675d5552e0ff0ULL;
  static const uint64_t static_value2 = 0x444fb567ca5dc17eULL;
};

template<class ContainerAllocator>
struct DataType< ::irisbot::NodeMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irisbot/NodeMsg";
  }

  static const char* value(const ::irisbot::NodeMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irisbot::NodeMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Node node\n\
string message\n\
\n\
================================================================================\n\
MSG: irisbot/Node\n\
int32 ID\n\
int32 addr\n\
string role\n\
";
  }

  static const char* value(const ::irisbot::NodeMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irisbot::NodeMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NodeMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irisbot::NodeMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irisbot::NodeMsg_<ContainerAllocator>& v)
  {
    s << indent << "node: ";
    s << std::endl;
    Printer< ::irisbot::Node_<ContainerAllocator> >::stream(s, indent + "  ", v.node);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRISBOT_MESSAGE_NODEMSG_H
